import { Persona } from "./persona";

export const PERSONE: Persona[] = [
    {
        id: 1,
        nome: "Vicky",
        cognome: "Fidoe",
        email: "vfidoe0@berkeley.edu",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Sales Associate", anno: 2007 },
            { nome: "Civil Engineer", anno: 2010 },
            { nome: "Design Engineer", anno: 2009 },
            { nome: "Account Executive", anno: 1965 },
            { nome: "Legal Assistant", anno: 1991 },
        ],
        lingue: [{ nome: "Portuguese" }],
    },
    {
        id: 2,
        nome: "Neill",
        cognome: "Jenckes",
        email: "njenckes1@instagram.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Recruiting Manager", anno: 1994 },
            { nome: "Software Test Engineer IV", anno: 1996 },
        ],
        lingue: [{ nome: "Lao" }, { nome: "Bosnian" }],
    },
    {
        id: 3,
        nome: "Meir",
        cognome: "Oda",
        email: "moda2@yandex.ru",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Editor", anno: 2001 },
            { nome: "Senior Developer", anno: 2005 },
            { nome: "Senior Sales Associate", anno: 1995 },
            { nome: "Research Assistant IV", anno: 1997 },
            { nome: "Engineer I", anno: 2012 },
        ],
        lingue: [{ nome: "Montenegrin" }, { nome: "Norwegian" }],
    },
    {
        id: 4,
        nome: "Valli",
        cognome: "Moniker",
        email: "vmoniker3@delicious.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Environmental Specialist", anno: 1997 },
            { nome: "Paralegal", anno: 2012 },
        ],
        lingue: [{ nome: "Croatian" }],
    },
    {
        id: 5,
        nome: "Jeremiah",
        cognome: "Benoist",
        email: "jbenoist4@marriott.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Software Consultant", anno: 1992 },
            { nome: "Help Desk Technician", anno: 1995 },
            { nome: "Cost Accountant", anno: 1996 },
        ],
        lingue: [{ nome: "Albanian" }, { nome: "Gagauz" }, { nome: "Yiddish" }],
    },
    {
        id: 6,
        nome: "Austin",
        cognome: "Whitcomb",
        email: "awhitcomb5@hugedomains.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "VP Accounting", anno: 1983 },
            { nome: "Database Administrator II", anno: 2011 },
            { nome: "Associate Professor", anno: 1967 },
        ],
        lingue: [{ nome: "Bengali" }, { nome: "Latvian" }],
    },
    {
        id: 7,
        nome: "Hamel",
        cognome: "Surfleet",
        email: "hsurfleet6@theguardian.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Financial Analyst", anno: 1992 },
            { nome: "Data Coordiator", anno: 2010 },
            { nome: "Web Designer III", anno: 2011 },
            { nome: "Cost Accountant", anno: 1994 },
            { nome: "Registered Nurse", anno: 2011 },
        ],
        lingue: [{ nome: "Aymara" }],
    },
    {
        id: 8,
        nome: "Jacob",
        cognome: "Bram",
        email: "jbram7@goo.ne.jp",
        sesso: "M",
        attivo: false,
        occupazioni: [{ nome: "Assistant Media Planner", anno: 2009 }],
        lingue: [
            { nome: "Māori" },
            { nome: "Dutch" },
            { nome: "Indonesian" },
            { nome: "Lithuanian" },
        ],
    },
    {
        id: 9,
        nome: "Mychal",
        cognome: "Wattingham",
        email: "mwattingham8@technorati.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Geologist IV", anno: 1997 },
            { nome: "Administrative Assistant I", anno: 2010 },
        ],
        lingue: [{ nome: "Greek" }, { nome: "Bislama" }],
    },
    {
        id: 10,
        nome: "Cyb",
        cognome: "Drover",
        email: "cdrover9@surveymonkey.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Mechanical Systems Engineer", anno: 1993 },
            { nome: "Payment Adjustment Coordinator", anno: 2004 },
            { nome: "Mechanical Systems Engineer", anno: 1988 },
            { nome: "Help Desk Operator", anno: 2009 },
            { nome: "Business Systems Development Analyst", anno: 2005 },
        ],
        lingue: [{ nome: "Belarusian" }, { nome: "Assamese" }],
    },
    {
        id: 11,
        nome: "Frederigo",
        cognome: "Baudry",
        email: "fbaudrya@deliciousdays.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "VP Accounting", anno: 1997 },
            { nome: "Quality Engineer", anno: 2009 },
            { nome: "VP Marketing", anno: 1995 },
        ],
        lingue: [{ nome: "Khmer" }],
    },
    {
        id: 12,
        nome: "Curtis",
        cognome: "Palatini",
        email: "cpalatinib@google.fr",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Geological Engineer", anno: 2005 },
            { nome: "Recruiter", anno: 1999 },
            { nome: "Clinical Specialist", anno: 2002 },
        ],
        lingue: [{ nome: "Telugu" }, { nome: "Tok Pisin" }],
    },
    {
        id: 13,
        nome: "Annmaria",
        cognome: "Gookes",
        email: "agookesc@mail.ru",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Financial Advisor", anno: 2013 },
            { nome: "GIS Technical Architect", anno: 1986 },
            { nome: "VP Marketing", anno: 1994 },
            { nome: "Engineer I", anno: 2010 },
            { nome: "Librarian", anno: 1994 },
        ],
        lingue: [{ nome: "Hebrew" }, { nome: "Hindi" }],
    },
    {
        id: 14,
        nome: "Agnola",
        cognome: "Hrinchenko",
        email: "ahrinchenkod@blogtalkradio.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Analog Circuit Design manager", anno: 2006 },
            { nome: "Analyst Programmer", anno: 2005 },
        ],
        lingue: [
            { nome: "Oriya" },
            { nome: "Somali" },
            { nome: "Hiri Motu" },
            { nome: "Dzongkha" },
        ],
    },
    {
        id: 15,
        nome: "Effie",
        cognome: "Riche",
        email: "erichee@noaa.gov",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "VP Quality Control", anno: 2000 },
            { nome: "GIS Technical Architect", anno: 2002 },
            { nome: "Health Coach II", anno: 2000 },
            { nome: "Nurse", anno: 2008 },
            { nome: "Food Chemist", anno: 2002 },
        ],
        lingue: [{ nome: "Filipino" }, { nome: "Kazakh" }, { nome: "Albanian" }],
    },
    {
        id: 16,
        nome: "Sigismundo",
        cognome: "Kolodziejski",
        email: "skolodziejskif@nba.com",
        sesso: "M",
        attivo: false,
        occupazioni: [{ nome: "Web Developer III", anno: 2005 }],
        lingue: [
            { nome: "German" },
            { nome: "Estonian" },
            { nome: "Swedish" },
            { nome: "Aymara" },
            { nome: "Fijian" },
        ],
    },
    {
        id: 17,
        nome: "Myrlene",
        cognome: "Sydall",
        email: "msydallg@linkedin.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Senior Quality Engineer", anno: 2004 },
            { nome: "VP Quality Control", anno: 2007 },
        ],
        lingue: [{ nome: "Bengali" }],
    },
    {
        id: 18,
        nome: "Reider",
        cognome: "Maidment",
        email: "rmaidmenth@live.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Help Desk Technician", anno: 2005 },
            { nome: "Administrative Officer", anno: 2009 },
            { nome: "Analog Circuit Design manager", anno: 1996 },
        ],
        lingue: [
            { nome: "Swati" },
            { nome: "English" },
            { nome: "English" },
            { nome: "Dari" },
            { nome: "Montenegrin" },
        ],
    },
    {
        id: 19,
        nome: "Bab",
        cognome: "Pratton",
        email: "bprattoni@bbc.co.uk",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Chemical Engineer", anno: 2008 },
            { nome: "Environmental Tech", anno: 1963 },
            { nome: "Teacher", anno: 2008 },
        ],
        lingue: [
            { nome: "Punjabi" },
            { nome: "Tajik" },
            { nome: "Estonian" },
            { nome: "Filipino" },
            { nome: "Malayalam" },
        ],
    },
    {
        id: 20,
        nome: "Waylan",
        cognome: "Dmitrievski",
        email: "wdmitrievskij@163.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Analyst Programmer", anno: 1968 },
            { nome: "Food Chemist", anno: 1994 },
            { nome: "Cost Accountant", anno: 1994 },
        ],
        lingue: [
            { nome: "Amharic" },
            { nome: "Hindi" },
            { nome: "Albanian" },
            { nome: "Hindi" },
        ],
    },
    {
        id: 21,
        nome: "Wendy",
        cognome: "Woollhead",
        email: "wwoollheadk@theguardian.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Civil Engineer", anno: 1999 },
            { nome: "Business Systems Development Analyst", anno: 1987 },
            { nome: "Biostatistician IV", anno: 1999 },
            { nome: "Payment Adjustment Coordinator", anno: 1999 },
        ],
        lingue: [
            { nome: "West Frisian" },
            { nome: "Filipino" },
            { nome: "Gagauz" },
        ],
    },
    {
        id: 22,
        nome: "Jason",
        cognome: "McDougal",
        email: "jmcdougall@imdb.com",
        sesso: "M",
        attivo: false,
        occupazioni: [
            { nome: "Director of Sales", anno: 2009 },
            { nome: "Project Manager", anno: 1994 },
        ],
        lingue: [{ nome: "Swahili" }, { nome: "Kyrgyz" }, { nome: "Aymara" }],
    },
    {
        id: 23,
        nome: "Ignacius",
        cognome: "Halpen",
        email: "ihalpenm@360.cn",
        sesso: "M",
        attivo: false,
        occupazioni: [{ nome: "Project Manager", anno: 2006 }],
        lingue: [{ nome: "Lithuanian" }],
    },
    {
        id: 24,
        nome: "Sammy",
        cognome: "Aynold",
        email: "saynoldn@google.com.hk",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Assistant Manager", anno: 2005 },
            { nome: "Media Manager I", anno: 2007 },
            { nome: "Food Chemist", anno: 2010 },
            { nome: "Product Engineer", anno: 1992 },
        ],
        lingue: [{ nome: "Dzongkha" }],
    },
    {
        id: 25,
        nome: "Sydel",
        cognome: "Hyndes",
        email: "shyndeso@nhs.uk",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Recruiting Manager", anno: 2009 },
            { nome: "Account Representative IV", anno: 2006 },
            { nome: "Editor", anno: 1995 },
        ],
        lingue: [
            { nome: "Spanish" },
            { nome: "Filipino" },
            { nome: "Sotho" },
            { nome: "Tsonga" },
        ],
    },
    {
        id: 26,
        nome: "Nada",
        cognome: "Rabley",
        email: "nrableyp@bigcartel.com",
        sesso: "F",
        attivo: false,
        occupazioni: [{ nome: "Nurse", anno: 2011 }],
        lingue: [{ nome: "Filipino" }, { nome: "Kazakh" }],
    },
    {
        id: 27,
        nome: "Jessie",
        cognome: "Keynes",
        email: "jkeynesq@ehow.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Help Desk Technician", anno: 1998 },
            { nome: "Staff Scientist", anno: 2003 },
            { nome: "Environmental Tech", anno: 2009 },
            { nome: "Account Executive", anno: 2003 },
        ],
        lingue: [{ nome: "Gagauz" }],
    },
    {
        id: 28,
        nome: "Catarina",
        cognome: "Balnave",
        email: "cbalnaver@techcrunch.com",
        sesso: "F",
        attivo: false,
        occupazioni: [{ nome: "Quality Engineer", anno: 2010 }],
        lingue: [
            { nome: "Kazakh" },
            { nome: "Bosnian" },
            { nome: "Spanish" },
            { nome: "Tok Pisin" },
        ],
    },
    {
        id: 29,
        nome: "Ivy",
        cognome: "Briztman",
        email: "ibriztmans@flickr.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Desktop Support Technician", anno: 2006 },
            { nome: "Help Desk Technician", anno: 2010 },
            { nome: "Nurse", anno: 2002 },
        ],
        lingue: [
            { nome: "Korean" },
            { nome: "Persian" },
            { nome: "Māori" },
            { nome: "Italian" },
            { nome: "Fijian" },
        ],
    },
    {
        id: 30,
        nome: "Willey",
        cognome: "Guyer",
        email: "wguyert@woothemes.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Media Manager II", anno: 2000 },
            { nome: "Help Desk Technician", anno: 1995 },
            { nome: "Information Systems Manager", anno: 1999 },
            { nome: "Nuclear Power Engineer", anno: 2007 },
            { nome: "VP Quality Control", anno: 2008 },
        ],
        lingue: [
            { nome: "French" },
            { nome: "Dari" },
            { nome: "Quechua" },
            { nome: "Norwegian" },
        ],
    },
    {
        id: 31,
        nome: "Lindsay",
        cognome: "Brissard",
        email: "lbrissardu@scribd.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Environmental Tech", anno: 1956 },
            { nome: "Media Manager IV", anno: 2010 },
            { nome: "Assistant Professor", anno: 1995 },
            { nome: "Geological Engineer", anno: 1995 },
            { nome: "Help Desk Operator", anno: 2007 },
        ],
        lingue: [
            { nome: "Spanish" },
            { nome: "Armenian" },
            { nome: "Hebrew" },
            { nome: "Hiri Motu" },
        ],
    },
    {
        id: 32,
        nome: "Jamey",
        cognome: "Billing",
        email: "jbillingv@feedburner.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Staff Accountant I", anno: 1997 },
            { nome: "Social Worker", anno: 2010 },
            { nome: "Technical Writer", anno: 2006 },
            { nome: "Payment Adjustment Coordinator", anno: 2004 },
            { nome: "Dental Hygienist", anno: 1996 },
        ],
        lingue: [{ nome: "Quechua" }, { nome: "Tetum" }, { nome: "Tajik" }],
    },
    {
        id: 33,
        nome: "Jennee",
        cognome: "Franklyn",
        email: "jfranklynw@moonfruit.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Office Assistant III", anno: 2012 },
            { nome: "Nuclear Power Engineer", anno: 2010 },
            { nome: "Financial Analyst", anno: 2004 },
            { nome: "Librarian", anno: 1994 },
            { nome: "Editor", anno: 2003 },
        ],
        lingue: [
            { nome: "Hiri Motu" },
            { nome: "Yiddish" },
            { nome: "Lao" },
            { nome: "Fijian" },
            { nome: "Czech" },
        ],
    },
    {
        id: 34,
        nome: "Tove",
        cognome: "Gobbett",
        email: "tgobbettx@hao123.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Accountant I", anno: 2012 },
            { nome: "Sales Representative", anno: 2008 },
            { nome: "Cost Accountant", anno: 2009 },
        ],
        lingue: [{ nome: "Amharic" }],
    },
    {
        id: 35,
        nome: "Dalli",
        cognome: "Dubock",
        email: "ddubocky@constantcontact.com",
        sesso: "M",
        attivo: true,
        occupazioni: [{ nome: "Librarian", anno: 2005 }],
        lingue: [{ nome: "Zulu" }, { nome: "Lao" }],
    },
    {
        id: 36,
        nome: "Hallie",
        cognome: "Jerson",
        email: "hjersonz@ed.gov",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Professor", anno: 1994 },
            { nome: "Desktop Support Technician", anno: 1994 },
            { nome: "Cost Accountant", anno: 2009 },
        ],
        lingue: [{ nome: "Icelandic" }],
    },
    {
        id: 37,
        nome: "Hubert",
        cognome: "Burges",
        email: "hburges10@php.net",
        sesso: "M",
        attivo: false,
        occupazioni: [
            { nome: "Electrical Engineer", anno: 2007 },
            { nome: "Food Chemist", anno: 2006 },
        ],
        lingue: [
            { nome: "Maltese" },
            { nome: "Irish Gaelic" },
            { nome: "Nepali" },
            { nome: "Kyrgyz" },
        ],
    },
    {
        id: 38,
        nome: "Austin",
        cognome: "Silcox",
        email: "asilcox11@intel.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Analog Circuit Design manager", anno: 2005 },
            { nome: "Nurse Practicioner", anno: 2004 },
            { nome: "Web Designer IV", anno: 2001 },
            { nome: "Compensation Analyst", anno: 1998 },
        ],
        lingue: [
            { nome: "French" },
            { nome: "Belarusian" },
            { nome: "Danish" },
            { nome: "Hiri Motu" },
            { nome: "Hebrew" },
        ],
    },
    {
        id: 39,
        nome: "Zachery",
        cognome: "Jefferson",
        email: "zjefferson12@businesswire.com",
        sesso: "M",
        attivo: false,
        occupazioni: [
            { nome: "Analyst Programmer", anno: 1988 },
            { nome: "Marketing Manager", anno: 2002 },
            { nome: "Financial Analyst", anno: 1996 },
        ],
        lingue: [{ nome: "Marathi" }],
    },
    {
        id: 40,
        nome: "Ariel",
        cognome: "Sclanders",
        email: "asclanders13@dailymotion.com",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Recruiting Manager", anno: 2010 },
            { nome: "GIS Technical Architect", anno: 1986 },
            { nome: "Environmental Tech", anno: 2008 },
            { nome: "Research Assistant I", anno: 2005 },
            { nome: "Electrical Engineer", anno: 2007 },
        ],
        lingue: [{ nome: "Latvian" }, { nome: "Polish" }, { nome: "Swahili" }],
    },
    {
        id: 41,
        nome: "Sari",
        cognome: "Lemmer",
        email: "slemmer14@hostgator.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Staff Scientist", anno: 2012 },
            { nome: "Payment Adjustment Coordinator", anno: 2010 },
            { nome: "General Manager", anno: 1994 },
            { nome: "Environmental Specialist", anno: 2006 },
            { nome: "Nurse", anno: 2005 },
        ],
        lingue: [{ nome: "Pashto" }, { nome: "Swedish" }, { nome: "Kazakh" }],
    },
    {
        id: 42,
        nome: "Shaine",
        cognome: "Kembry",
        email: "skembry15@domainmarket.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Associate Professor", anno: 1986 },
            { nome: "Information Systems Manager", anno: 1990 },
        ],
        lingue: [
            { nome: "Punjabi" },
            { nome: "Northern Sotho" },
            { nome: "Hungarian" },
            { nome: "Hebrew" },
            { nome: "Croatian" },
        ],
    },
    {
        id: 43,
        nome: "Andree",
        cognome: "Hayselden",
        email: "ahayselden16@merriam-webster.com",
        sesso: "F",
        attivo: false,
        occupazioni: [
            { nome: "Registered Nurse", anno: 1992 },
            { nome: "GIS Technical Architect", anno: 2006 },
        ],
        lingue: [{ nome: "Mongolian" }],
    },
    {
        id: 44,
        nome: "Hy",
        cognome: "Loker",
        email: "hloker17@bandcamp.com",
        sesso: "M",
        attivo: false,
        occupazioni: [{ nome: "General Manager", anno: 1994 }],
        lingue: [
            { nome: "West Frisian" },
            { nome: "Estonian" },
            { nome: "Korean" },
            { nome: "Kashmiri" },
            { nome: "Amharic" },
        ],
    },
    {
        id: 45,
        nome: "Antonina",
        cognome: "Ameer-Beg",
        email: "aameerbeg18@mtv.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Structural Analysis Engineer", anno: 2009 },
            { nome: "Geologist I", anno: 1982 },
            { nome: "Structural Engineer", anno: 2010 },
            { nome: "Sales Associate", anno: 2006 },
        ],
        lingue: [
            { nome: "Arabic" },
            { nome: "Northern Sotho" },
            { nome: "West Frisian" },
            { nome: "Oriya" },
            { nome: "French" },
        ],
    },
    {
        id: 46,
        nome: "Hermine",
        cognome: "Vase",
        email: "hvase19@creativecommons.org",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Payment Adjustment Coordinator", anno: 1999 },
            { nome: "Quality Engineer", anno: 2012 },
            { nome: "Account Representative I", anno: 2006 },
            { nome: "Database Administrator I", anno: 2006 },
        ],
        lingue: [{ nome: "Finnish" }],
    },
    {
        id: 47,
        nome: "Jo-anne",
        cognome: "Bickley",
        email: "jbickley1a@odnoklassniki.ru",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "VP Product Management", anno: 1999 },
            { nome: "Database Administrator I", anno: 1985 },
        ],
        lingue: [{ nome: "Sotho" }, { nome: "Kyrgyz" }, { nome: "Finnish" }],
    },
    {
        id: 48,
        nome: "Homer",
        cognome: "Crossgrove",
        email: "hcrossgrove1b@yahoo.co.jp",
        sesso: "M",
        attivo: false,
        occupazioni: [
            { nome: "Human Resources Assistant IV", anno: 2008 },
            { nome: "VP Sales", anno: 2010 },
        ],
        lingue: [
            { nome: "Hindi" },
            { nome: "Luxembourgish" },
            { nome: "Hungarian" },
            { nome: "Dutch" },
            { nome: "Montenegrin" },
        ],
    },
    {
        id: 49,
        nome: "Arlina",
        cognome: "Schroder",
        email: "aschroder1c@weibo.com",
        sesso: "F",
        attivo: true,
        occupazioni: [
            { nome: "Media Manager II", anno: 1995 },
            { nome: "Account Coordinator", anno: 1997 },
            { nome: "VP Quality Control", anno: 1999 },
            { nome: "Developer IV", anno: 1986 },
        ],
        lingue: [{ nome: "Finnish" }, { nome: "Malay" }, { nome: "Thai" }],
    },
    {
        id: 50,
        nome: "Sansone",
        cognome: "Waterland",
        email: "swaterland1d@hhs.gov",
        sesso: "M",
        attivo: true,
        occupazioni: [
            { nome: "Help Desk Technician", anno: 1984 },
            { nome: "Mechanical Systems Engineer", anno: 2006 },
            { nome: "Programmer Analyst III", anno: 2001 },
        ],
        lingue: [{ nome: "Kashmiri" }],
    },
];
